name: "BMS Volta V2.1 - Development"
description: "Volta V2.1 BMS Interface"
version: "2.2.4dev"
slug: "bms_volta_dev"
url: "https://github.com/Tertiush/bmspace/volta-sg1-bms-dev"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true

options:
  mqtt_host: "192.168.0.15"
  mqtt_port: 1883
  mqtt_user: "mqtt-users"
  mqtt_password: "mqtt-users"
  mqtt_ha_discovery: true
  mqtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "bmspace"
  connection_type: "IP"
  bms_ip: "192.168.0.22"
  bms_port: 5000
  bms_serial: "/dev/ttyUSB0"
  scan_interval: 5
  debug_output: 0
  packs_to_read: 1
  force_pack_offset: 0
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_ha_discovery: bool
  mqtt_ha_discovery_topic: str
  mqtt_base_topic: str
  connection_type: list(IP|Serial)
  bms_ip: str
  bms_port: int
  bms_serial: str
  scan_interval: int
  debug_output: int
  packs_to_read: int
  force_pack_offset: "int?"
